# frozen_string_literal: true
#
# This file is generated by script/generate_catalog.rb from
# references/source/constants/bank-apps.ts.
# Do not edit it by hand.

module VietnamQrPay
  # Supported mobile app metadata associated with the source catalog.
  BANK_APPS = [
  BankApp.new(
      bank: BankKey::ABBANK,
      scheme: "abbankmobile",
      package_id: "com.vnpay.abbank",
      app_store_id: "id1137160023",
      support_viet_qr: true,
      support_vnpay_qr: true
  ).freeze,
  BankApp.new(
      bank: BankKey::ACB,
      scheme: "acbapp",
      package_id: "mobile.acb.com.vn",
      app_store_id: "id950141024",
      support_viet_qr: true,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::AGRIBANK,
      scheme: "agribankmobile",
      package_id: "com.vnpay.Agribank3g",
      app_store_id: "id935944952",
      support_viet_qr: true,
      support_vnpay_qr: true
  ).freeze,
  BankApp.new(
      bank: BankKey::BAC_A_BANK,
      package_id: "com.bab.retailUAT",
      app_store_id: "id1441408786",
      support_viet_qr: false,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::BAOVIET_BANK,
      scheme: "baovietmobile",
      package_id: "com.vnpay.bvbank",
      app_store_id: "id1504422967",
      support_viet_qr: true,
      support_vnpay_qr: true
  ).freeze,
  BankApp.new(
      bank: BankKey::BIDC,
      scheme: "bidcvnmobile",
      package_id: "com.vnpay.bidc",
      app_store_id: "id1043501726",
      support_viet_qr: false,
      support_vnpay_qr: true
  ).freeze,
  BankApp.new(
      bank: BankKey::BIDV,
      scheme: "bidvsmartbanking",
      package_id: "com.vnpay.bidv",
      app_store_id: "id1061867449",
      support_viet_qr: true,
      support_vnpay_qr: true
  ).freeze,
  BankApp.new(
      bank: BankKey::CAKE,
      scheme: "cake.vn",
      package_id: "xyz.be.cake",
      app_store_id: "id1551907051",
      support_viet_qr: true,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::CBBANK,
      package_id: "cbbank.vn.mobile",
      app_store_id: "id1531443181",
      support_viet_qr: false,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::CIMB,
      scheme: "cimb",
      package_id: "vn.cimbbank.octo",
      app_store_id: "id1318127958",
      support_viet_qr: true,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::COOP_BANK,
      scheme: "coopbankmobile",
      package_id: "com.vnpay.coopbank",
      app_store_id: "id1578445811",
      support_viet_qr: true,
      support_vnpay_qr: true
  ).freeze,
  BankApp.new(
      bank: BankKey::DBS_BANK,
      package_id: "com.dbs.sg.dbsmbanking",
      app_store_id: "id1068403826",
      support_viet_qr: false,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::DONG_A_BANK,
      package_id: "com.dongabank.mobilenternet",
      app_store_id: "id993124125",
      support_viet_qr: false,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::EXIMBANK,
      scheme: "eximbankmobile",
      package_id: "com.vnpay.eximbank",
      app_store_id: "id1242260338",
      support_viet_qr: true,
      support_vnpay_qr: true
  ).freeze,
  BankApp.new(
      bank: BankKey::GPBANK,
      support_viet_qr: false,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::HDBANK,
      scheme: "hdbankmobile",
      package_id: "com.vnpay.hdbank",
      app_store_id: "id1461658565",
      support_viet_qr: true,
      support_vnpay_qr: true
  ).freeze,
  BankApp.new(
      bank: BankKey::HONGLEONG_BANK,
      package_id: "my.com.hongleongconnect.mobileconnect",
      app_store_id: "id1446719260",
      support_viet_qr: false,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::HSBC,
      package_id: "vn.hsbc.hsbcvietnam",
      app_store_id: "id1472163155",
      support_viet_qr: false,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::IBK_HCM,
      scheme: "ionebankglobal",
      package_id: "com.ibk.neobanking.mini",
      app_store_id: "id787064809",
      support_viet_qr: true,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::INDOVINA_BANK,
      scheme: "ivbmobilebanking",
      package_id: "com.vnpay.ivb",
      app_store_id: "id1096963960",
      support_viet_qr: true,
      support_vnpay_qr: true
  ).freeze,
  BankApp.new(
      bank: BankKey::KASIKORN_BANK,
      package_id: "com.kasikornbank.kplus.vn",
      app_store_id: "id1586576195",
      support_viet_qr: false,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::KIENLONG_BANK,
      scheme: "kienlongbankmobilebanking",
      package_id: "com.sunshine.ksbank",
      app_store_id: "id1562823941",
      support_viet_qr: true,
      support_vnpay_qr: true
  ).freeze,
  BankApp.new(
      bank: BankKey::KOOKMIN_BANK_HCM,
      package_id: "com.kbstar.global",
      app_store_id: "id1542727700",
      support_viet_qr: false,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::LIENVIETPOST_BANK,
      scheme: "lv24h",
      package_id: "vn.com.lpb.lienviet24h",
      app_store_id: "id1488794748",
      support_viet_qr: true,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::LPBANK,
      scheme: "lv24h",
      package_id: "vn.com.lpb.lienviet24h",
      app_store_id: "id1488794748",
      support_viet_qr: true,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::LIOBANK,
      scheme: "lio",
      package_id: "com.ocb.liobank",
      app_store_id: "id6444787281",
      support_viet_qr: true,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::MBBANK,
      scheme: "mbmobile",
      package_id: "com.mbmobile",
      app_store_id: "id1205807363",
      support_viet_qr: true,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::MBV,
      scheme: "oceanbankmobilebanking",
      package_id: "com.vnpay.ocean",
      app_store_id: "id1469028843",
      support_viet_qr: true,
      support_vnpay_qr: true
  ).freeze,
  BankApp.new(
      bank: BankKey::MSB,
      scheme: "msbmobile",
      package_id: "vn.com.msb.smartBanking",
      app_store_id: "id436134873",
      support_viet_qr: false,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::NAM_A_BANK,
      scheme: "deeplinkapp",
      package_id: "ops.namabank.com.vn",
      app_store_id: "id1456997296",
      support_viet_qr: true,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::NCB,
      scheme: "ncbizimobile",
      package_id: "com.ncb.bank",
      app_store_id: "id1465217154",
      support_viet_qr: true,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::NONGHYUP_BANK_HN,
      scheme: "newnhsmartbanking",
      package_id: "nh.smart.banking",
      app_store_id: "id1444712671",
      support_viet_qr: true,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::OCB,
      scheme: "omniapp",
      package_id: "com.ocb.omniextra",
      app_store_id: "id1358682577",
      support_viet_qr: true,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::OCEANBANK,
      scheme: "oceanbankmobilebanking",
      package_id: "com.vnpay.ocean",
      app_store_id: "id1469028843",
      support_viet_qr: true,
      support_vnpay_qr: true
  ).freeze,
  BankApp.new(
      bank: BankKey::PGBANK,
      package_id: "pgbankApp.pgbank.com.vn",
      app_store_id: "id1537765475",
      support_viet_qr: false,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::PUBLIC_BANK,
      scheme: "publicbankmobile",
      package_id: "com.vnpay.publicbank",
      app_store_id: "id1573736472",
      support_viet_qr: true,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::PVCOM_BANK,
      scheme: "pvcombankapp",
      package_id: "com.vsii.pvcombank",
      app_store_id: "id957284067",
      support_viet_qr: true,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::SACOMBANK,
      scheme: "sacombankmobile",
      package_id: "src.com.sacombank",
      app_store_id: "id885814869",
      support_viet_qr: true,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::SAIGONBANK,
      scheme: "Sgbmobile",
      package_id: "com.vnpay.sgbank",
      app_store_id: "id1481832587",
      support_viet_qr: true,
      support_vnpay_qr: true
  ).freeze,
  BankApp.new(
      bank: BankKey::SCB,
      scheme: "scbmobilebanking",
      package_id: "com.vnpay.SCB",
      app_store_id: "id954973621",
      support_viet_qr: true,
      support_vnpay_qr: true
  ).freeze,
  BankApp.new(
      bank: BankKey::SEA_BANK,
      scheme: "seabankmobile",
      package_id: "vn.com.seabank.mb1",
      app_store_id: "id846407152",
      support_viet_qr: true,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::SHB,
      scheme: "shbmobile",
      package_id: "vn.shb.mbanking",
      app_store_id: "id538278798",
      support_viet_qr: true,
      support_vnpay_qr: true
  ).freeze,
  BankApp.new(
      bank: BankKey::SHINHAN_BANK,
      scheme: "shinhanglbvnbank",
      package_id: "com.shinhan.global.vn.bank",
      app_store_id: "id1071033810",
      support_viet_qr: true,
      support_vnpay_qr: true
  ).freeze,
  BankApp.new(
      bank: BankKey::STANDARD_CHARTERED_BANK,
      package_id: "com.sc.mobilebanking.vn",
      app_store_id: "id1146741999",
      support_viet_qr: false,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::TECHCOMBANK,
      scheme: "tcb",
      package_id: "vn.com.techcombank.bb.app",
      app_store_id: "id1548623362",
      support_viet_qr: true,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::TIMO,
      scheme: "plus",
      package_id: "io.lifestyle.plus",
      app_store_id: "id1521230347",
      support_viet_qr: true,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::TPBANK,
      scheme: "tpbankmobile",
      package_id: "com.tpbankquickpay",
      app_store_id: "id1292194225",
      support_viet_qr: false,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::TPBANK,
      scheme: "hydro",
      package_id: "com.tpb.mb.gprsandroid",
      app_store_id: "id450464147",
      support_viet_qr: true,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::UBANK,
      package_id: "vn.vpbank.ubank",
      app_store_id: "id1529056628",
      support_viet_qr: false,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::UNITED_OVERSEAS_BANK,
      scheme: "mightyapp",
      package_id: "com.uob.mightyvn",
      app_store_id: "id1174327324",
      support_viet_qr: true,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::VIB,
      scheme: "myvib2",
      package_id: "com.vib.myvib2",
      app_store_id: "id1626624790",
      support_viet_qr: true,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::VIET_A_BANK,
      scheme: "vabmobilebanking",
      package_id: "phn.com.vn.mb",
      app_store_id: "id910897337",
      support_viet_qr: true,
      support_vnpay_qr: true
  ).freeze,
  BankApp.new(
      bank: BankKey::VIET_BANK,
      scheme: "vietbankmobilebanking",
      package_id: "com.vnpay.vietbank",
      app_store_id: "id1461658565",
      support_viet_qr: true,
      support_vnpay_qr: true
  ).freeze,
  BankApp.new(
      bank: BankKey::BANVIET,
      scheme: "bvbankdigimi",
      package_id: "vn.banvietbank.mobilebanking",
      app_store_id: "id1526444697",
      support_viet_qr: true,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::VIETCOMBANK,
      scheme: "vietcombankmobile",
      package_id: "com.VCB",
      app_store_id: "id561433133",
      support_viet_qr: true,
      support_vnpay_qr: true
  ).freeze,
  BankApp.new(
      bank: BankKey::VIETINBANK,
      scheme: "vietinbankmobile",
      package_id: "com.vietinbank.ipay",
      app_store_id: "id689963454",
      support_viet_qr: true,
      support_vnpay_qr: true
  ).freeze,
  BankApp.new(
      bank: BankKey::VIKKI,
      scheme: "vikki",
      package_id: "com.finx.vikki",
      app_store_id: "id6471952024",
      support_viet_qr: true,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::VPBANK,
      scheme: "vpbankneo",
      package_id: "com.vnpay.vpbankonline",
      app_store_id: "id1209349510",
      support_viet_qr: true,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::VRB,
      support_viet_qr: false,
      support_vnpay_qr: false
  ).freeze,
  BankApp.new(
      bank: BankKey::WOORI_BANK,
      scheme: "wvbs",
      package_id: "vn.com.woori.smart",
      app_store_id: "id1501785125",
      support_viet_qr: true,
      support_vnpay_qr: false
  ).freeze
  ].freeze
  BankApps = BANK_APPS
end
