# frozen_string_literal: true

require "pathname"

# Generates the Ruby catalog files from the bundled source constants. This
# keeps the large bank/app constant surfaces synchronized without hand-editing
# generated Ruby files.
ROOT = Pathname(__dir__).join("..").expand_path
REFERENCE = ROOT.join("references/source/constants")
OUTPUT = ROOT.join("lib/vietnam_qr_pay/catalog")

def parse_enum(path)
  content = path.read
  body = content[/export enum \w+ \{(.*)\n\}/m, 1]
  raise "Unable to parse enum from #{path}" unless body

  body.scan(/^\s*(?:\/\*\*.*?\*\/\s*)?([A-Z0-9_]+)\s*=\s*'([^']+)'/m)
end

def parse_value(raw)
  # The upstream reference mixes strings, booleans, numbers, nulls, and enum
  # references. We normalize them into simple Ruby literals or tagged tuples so
  # the renderer can emit the correct constant references later.
  value = raw.sub(/,\s*\z/, "").sub(%r{\s*//.*\z}, "").strip
  return nil if value == "null"
  return true if value == "true"
  return false if value == "false"
  return value.to_i if value.match?(/\A-?\d+\z/)
  return [:bank_key, Regexp.last_match(1)] if value =~ /\ABankKey\.([A-Z0-9_]+)\z/
  return [:bank_code, Regexp.last_match(1)] if value =~ /\ABankCode\.([A-Z0-9_]+)\z/
  return [:viet_qr_status, Regexp.last_match(1)] if value =~ /\AVietQRStatus\.([A-Z0-9_]+)\z/
  return value[1..-2] if value.start_with?("'") && value.end_with?("'")

  raise "Unsupported value: #{value}"
end

def parse_key_value_lines(block)
  # Generated source objects are simple enough to parse line by line here,
  # which keeps the sync script dependency-free.
  block.each_line.filter_map do |line|
    stripped = line.strip
    next if stripped.empty? || stripped.start_with?("/**") || stripped.start_with?("*")

    match = stripped.match(/\A([A-Za-z0-9_]+):\s*(.+)\z/)
    next unless match

    [match[1], parse_value(match[2])]
  end.to_h
end

def camel_to_snake(value)
  # Preserve the common QR acronyms with predictable Ruby names.
  return "viet_qr_status" if value == "vietQRStatus"
  return "support_viet_qr" if value == "supportVietQR"
  return "support_vnpay_qr" if value == "supportVNPayQR"

  value
    .gsub(/([A-Z\d]+)([A-Z][a-z])/, '\1_\2')
    .gsub(/([a-z\d])([A-Z])/, '\1_\2')
    .downcase
end

def ruby_literal(value)
  case value
  when nil
    "nil"
  when true, false, Integer
    value.inspect
  when Array
    type, constant = value
    case type
    when :bank_key then "BankKey::#{constant}"
    when :bank_code then "BankCode::#{constant}"
    when :viet_qr_status then "VietQRStatus::#{constant}"
    else raise "Unsupported constant tuple: #{value.inspect}"
    end
  else
    value.inspect
  end
end

def write_file(path, contents)
  path.dirname.mkpath
  path.write(contents)
end

BANK_KEY_VALUES = parse_enum(REFERENCE.join("bank-key.ts")).to_h.freeze

def build_bank_keys
  entries = BANK_KEY_VALUES.to_a
  lines = entries.map { |name, value| "    #{name} = #{value.inspect}" }
  <<~RUBY
    # frozen_string_literal: true
    #
    # This file is generated by script/generate_catalog.rb from
    # references/source/constants/bank-key.ts.
    # Do not edit it by hand.

    module VietnamQrPay
      # Source bank identifiers preserved for API compatibility.
      module BankKey
    #{lines.join("\n")}
      end
    end
  RUBY
end

def build_bank_codes
  entries = parse_enum(REFERENCE.join("bank-code.ts"))
  lines = entries.map { |name, value| "    #{name} = #{value.inspect}" }
  <<~RUBY
    # frozen_string_literal: true
    #
    # This file is generated by script/generate_catalog.rb from
    # references/source/constants/bank-code.ts.
    # Do not edit it by hand.

    module VietnamQrPay
      # Source bank code values preserved for API compatibility.
      module BankCode
    #{lines.join("\n")}
      end
    end
  RUBY
end

def build_banks
  content = REFERENCE.join("banks.ts").read
  blocks = content.scan(/\[BankKey\.[A-Z0-9_]+\]:\s*\{(.*?)\n\s*\}(?:,|\n)/m).map(&:first)
  keys = content.scan(/\[BankKey\.([A-Z0-9_]+)\]:\s*\{/).flatten

  entries = keys.zip(blocks).map do |key_name, block|
    attributes = parse_key_value_lines(block).transform_keys { |key| camel_to_snake(key) }
    literal_lines = attributes.map do |name, value|
      "      #{name}: #{ruby_literal(value)}"
    end

    <<~RUBY.chomp
      #{BANK_KEY_VALUES.fetch(key_name).to_sym.inspect} => Bank.new(
    #{literal_lines.join(",\n")}
      ).freeze
    RUBY
  end

  <<~RUBY
    # frozen_string_literal: true
    #
    # This file is generated by script/generate_catalog.rb from
    # references/source/constants/banks.ts.
    # Do not edit it by hand.

    module VietnamQrPay
      # VietQR support flags exposed by the source catalog.
      module VietQRStatus
        NOT_SUPPORTED = -1
        RECEIVE_ONLY = 0
        TRANSFER_SUPPORTED = 1
      end

      # Hash-style lookup keyed by the source bank identifier.
      BANKS_OBJECT = {
    #{entries.join(",\n")}
      }.freeze
      BanksObject = BANKS_OBJECT

      # Array-style catalog for callers that prefer iteration.
      BANKS = BANKS_OBJECT.values.freeze
      Banks = BANKS
    end
  RUBY
end

def build_bank_apps
  content = REFERENCE.join("bank-apps.ts").read
  array_body = content[/export const BankApps: BankApp\[\] = \[(.*)\]\s*\z/m, 1]
  raise "Unable to parse bank apps array" unless array_body

  blocks = array_body.scan(/\{\n(.*?)\n\s*\}(?:,|\n)/m).map(&:first)
  entries = blocks.map do |block|
    attributes = parse_key_value_lines(block).transform_keys { |key| camel_to_snake(key) }
    literal_lines = attributes.map do |name, value|
      "      #{name}: #{ruby_literal(value)}"
    end

    <<~RUBY.chomp
      BankApp.new(
    #{literal_lines.join(",\n")}
      ).freeze
    RUBY
  end

  <<~RUBY
    # frozen_string_literal: true
    #
    # This file is generated by script/generate_catalog.rb from
    # references/source/constants/bank-apps.ts.
    # Do not edit it by hand.

    module VietnamQrPay
      # Supported mobile app metadata associated with the source catalog.
      BANK_APPS = [
    #{entries.join(",\n")}
      ].freeze
      BankApps = BANK_APPS
    end
  RUBY
end

write_file(OUTPUT.join("bank_keys.rb"), build_bank_keys)
write_file(OUTPUT.join("bank_codes.rb"), build_bank_codes)
write_file(OUTPUT.join("banks.rb"), build_banks)
write_file(OUTPUT.join("bank_apps.rb"), build_bank_apps)
